name : cron-workflow

on:
  schedule:
    - cron: "* * * * *"
  
jobs:
  cron-workflow:
    runs-on: ubuntu-latest
    steps:
     - name: Test cron
       run : echo " Hello Every 1 min is runing "
        
