name: first workflow
on:
  push:
    branches:
      - "main"
jobs: 
  first-workflow:
    name: first-workflow
    runs-on: ubuntu-latest
    steps:
      - name: command run
        run: echo "first workflow"
    
  
  