name: first workflow
on:
  push:
    branches:
      - "main"
jobs: 
  first-workflow:
    name: first-workflow
    runs-on: ubuntu-latest
    steps:
      - name: before checkout
        run: ls

      - name: checkout
        uses: action/checkout@v3

      - name: after checkout
        run: ls
    
  
  